### ISSUE TITLE
Add Users Table similar to the one in lab07c

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs56-f19/ucsb-courses-search#28]
- [ ] Set up repo with database
- [ ] Add an entity repository and controller for users
- [ ] Add view for users
- [ ] Add code that populates user table

**Comment by pconrad** [comment]
See lab07c for details

**Comment by justintjoa** [comment]
Table has been created, click Schedule and See Your Schedule on dropdown to view a proto table
